export const farmhouses = [
  {
    id: "fh-001",
    name: "Sunset Valley Estate",
    slug: "sunset-valley-estate",
    description: "A luxurious farmhouse with stunning sunset views, infinity pool, and acres of manicured gardens. Perfect for family gatherings, corporate retreats, and celebrations.",
    images: ["/images/farmhouse-1.jpg", "/images/farmhouse-2.jpg", "/images/farmhouse-3.jpg"],
    location: {
      address: "123 Green Valley Road",
      city: "Lonavala",
      state: "Maharashtra",
      pincode: "410401",
      coordinates: { lat: 18.7546, lng: 73.4062 },
    },
    amenities: [
      { name: "Swimming Pool", icon: "waves", available: true },
      { name: "BBQ Area", icon: "flame", available: true },
      { name: "Garden", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Kitchen", icon: "chef-hat", available: true },
      { name: "Music System", icon: "music", available: true },
      { name: "Sports Turf", icon: "trophy", available: true },
    ],
    capacity: { minGuests: 5, maxGuests: 50 },
    pricing: {
      hourly: { "4hr": 8000, "6hr": 11000, "8hr": 14000, "12hr": 18000 },
      fullDay: 25000,
      weekendMultiplier: 1.3,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 250, menu: "Continental & Indian" },
      { meal: "Lunch", available: true, price: 450, menu: "Multi-cuisine buffet" },
      { meal: "Dinner", available: true, price: 500, menu: "BBQ & Fine dining" },
    ],
    rules: {
      checkInTime: "10:00 AM",
      checkOutTime: "9:00 AM",
      cancellationPolicy: "Free cancellation up to 48 hours before check-in",
      securityDeposit: 5000,
      petsAllowed: true,
      alcoholAllowed: true,
      smokingAllowed: false,
    },
    rating: { average: 4.8, count: 127 },
    totalBookings: 342,
    views: 5890,
    featured: true,
    instantBooking: true,
    status: "approved",
    adminId: "admin-001",
    createdAt: "2025-06-15",
  },
  {
    id: "fh-002",
    name: "Riverside Retreat",
    slug: "riverside-retreat",
    description: "Nestled alongside a serene river, this charming farmhouse offers a peaceful escape with nature trails, bonfire nights, and premium amenities.",
    images: ["/images/farmhouse-4.jpg", "/images/farmhouse-5.jpg", "/images/farmhouse-6.jpg"],
    location: {
      address: "456 River Lane",
      city: "Karjat",
      state: "Maharashtra",
      pincode: "410201",
      coordinates: { lat: 18.9107, lng: 73.3243 },
    },
    amenities: [
      { name: "River Access", icon: "waves", available: true },
      { name: "Bonfire", icon: "flame", available: true },
      { name: "Nature Trails", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Kitchen", icon: "chef-hat", available: true },
      { name: "Projector", icon: "monitor", available: true },
    ],
    capacity: { minGuests: 2, maxGuests: 30 },
    pricing: {
      hourly: { "4hr": 5000, "6hr": 7000, "8hr": 9000, "12hr": 12000 },
      fullDay: 16000,
      weekendMultiplier: 1.25,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 200, menu: "South Indian & Continental" },
      { meal: "Lunch", available: true, price: 350, menu: "Home-style cooking" },
      { meal: "Dinner", available: true, price: 400, menu: "BBQ special" },
    ],
    rules: {
      checkInTime: "11:00 AM",
      checkOutTime: "10:00 AM",
      cancellationPolicy: "Free cancellation up to 24 hours before check-in",
      securityDeposit: 3000,
      petsAllowed: false,
      alcoholAllowed: true,
      smokingAllowed: false,
    },
    rating: { average: 4.6, count: 89 },
    totalBookings: 215,
    views: 3420,
    featured: true,
    instantBooking: false,
    status: "approved",
    adminId: "admin-002",
    createdAt: "2025-08-20",
  },
  {
    id: "fh-003",
    name: "Hilltop Haven",
    slug: "hilltop-haven",
    description: "Perched atop a scenic hill, this modern farmhouse boasts panoramic views, a rooftop terrace, and a state-of-the-art entertainment system.",
    images: ["/images/farmhouse-3.jpg", "/images/farmhouse-1.jpg", "/images/farmhouse-5.jpg"],
    location: {
      address: "789 Hilltop Drive",
      city: "Igatpuri",
      state: "Maharashtra",
      pincode: "422403",
      coordinates: { lat: 19.6947, lng: 73.5627 },
    },
    amenities: [
      { name: "Rooftop Terrace", icon: "sun", available: true },
      { name: "Home Theater", icon: "monitor", available: true },
      { name: "Garden", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Jacuzzi", icon: "waves", available: true },
    ],
    capacity: { minGuests: 4, maxGuests: 25 },
    pricing: {
      hourly: { "4hr": 6000, "6hr": 8500, "8hr": 11000, "12hr": 15000 },
      fullDay: 20000,
      weekendMultiplier: 1.4,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 300, menu: "English & Indian" },
      { meal: "Dinner", available: true, price: 550, menu: "Chef special" },
    ],
    rules: {
      checkInTime: "2:00 PM",
      checkOutTime: "11:00 AM",
      cancellationPolicy: "Free cancellation up to 72 hours before check-in",
      securityDeposit: 7000,
      petsAllowed: true,
      alcoholAllowed: true,
      smokingAllowed: false,
    },
    rating: { average: 4.9, count: 64 },
    totalBookings: 156,
    views: 4120,
    featured: true,
    instantBooking: true,
    status: "approved",
    adminId: "admin-003",
    createdAt: "2025-04-10",
  },
  {
    id: "fh-004",
    name: "Green Meadows Farm",
    slug: "green-meadows-farm",
    description: "Sprawling farm with organic gardens, a large swimming pool, cricket turf, and rustic charm. Ideal for large groups and celebrations.",
    images: ["/images/farmhouse-6.jpg", "/images/farmhouse-2.jpg", "/images/farmhouse-4.jpg"],
    location: {
      address: "321 Meadow Way",
      city: "Alibaug",
      state: "Maharashtra",
      pincode: "402201",
      coordinates: { lat: 18.6414, lng: 72.8696 },
    },
    amenities: [
      { name: "Swimming Pool", icon: "waves", available: true },
      { name: "Cricket Turf", icon: "trophy", available: true },
      { name: "Organic Garden", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Kitchen", icon: "chef-hat", available: true },
      { name: "Badminton Court", icon: "trophy", available: true },
    ],
    capacity: { minGuests: 10, maxGuests: 80 },
    pricing: {
      hourly: { "4hr": 12000, "6hr": 16000, "8hr": 20000, "12hr": 26000 },
      fullDay: 35000,
      weekendMultiplier: 1.35,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 200, menu: "Farm-fresh" },
      { meal: "Lunch", available: true, price: 400, menu: "Traditional Maharashtrian" },
      { meal: "Dinner", available: true, price: 450, menu: "Barbecue & grills" },
      { meal: "Snacks", available: true, price: 150, menu: "Vada pav & chai" },
    ],
    rules: {
      checkInTime: "9:00 AM",
      checkOutTime: "8:00 AM",
      cancellationPolicy: "50% refund up to 48 hours before check-in",
      securityDeposit: 10000,
      petsAllowed: false,
      alcoholAllowed: true,
      smokingAllowed: false,
    },
    rating: { average: 4.5, count: 203 },
    totalBookings: 498,
    views: 8230,
    featured: false,
    instantBooking: true,
    status: "approved",
    adminId: "admin-004",
    createdAt: "2025-02-01",
  },
  {
    id: "fh-005",
    name: "Serenity Springs",
    slug: "serenity-springs",
    description: "A hidden gem with natural springs, zen gardens, and a spa-like atmosphere. Perfect for couples and small groups seeking tranquility.",
    images: ["/images/farmhouse-5.jpg", "/images/farmhouse-3.jpg", "/images/farmhouse-1.jpg"],
    location: {
      address: "567 Spring Lane",
      city: "Panchgani",
      state: "Maharashtra",
      pincode: "412805",
      coordinates: { lat: 17.9240, lng: 73.7995 },
    },
    amenities: [
      { name: "Natural Springs", icon: "waves", available: true },
      { name: "Spa", icon: "heart", available: true },
      { name: "Zen Garden", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Yoga Deck", icon: "sun", available: true },
    ],
    capacity: { minGuests: 2, maxGuests: 15 },
    pricing: {
      hourly: { "4hr": 4000, "6hr": 5500, "8hr": 7000, "12hr": 10000 },
      fullDay: 14000,
      weekendMultiplier: 1.2,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 350, menu: "Organic & healthy" },
      { meal: "Lunch", available: true, price: 500, menu: "Farm-to-table" },
      { meal: "Dinner", available: true, price: 600, menu: "Fine dining" },
    ],
    rules: {
      checkInTime: "12:00 PM",
      checkOutTime: "11:00 AM",
      cancellationPolicy: "Free cancellation up to 7 days before check-in",
      securityDeposit: 3000,
      petsAllowed: false,
      alcoholAllowed: false,
      smokingAllowed: false,
    },
    rating: { average: 4.9, count: 45 },
    totalBookings: 98,
    views: 2650,
    featured: true,
    instantBooking: false,
    status: "approved",
    adminId: "admin-005",
    createdAt: "2025-10-05",
  },
  {
    id: "fh-006",
    name: "Royal Orchid Villa",
    slug: "royal-orchid-villa",
    description: "A palatial farmhouse with grand interiors, a ballroom, heated pool, and lush orchid gardens. The ultimate luxury for milestone celebrations.",
    images: ["/images/farmhouse-2.jpg", "/images/farmhouse-6.jpg", "/images/farmhouse-4.jpg"],
    location: {
      address: "890 Orchid Boulevard",
      city: "Nashik",
      state: "Maharashtra",
      pincode: "422001",
      coordinates: { lat: 19.9975, lng: 73.7898 },
    },
    amenities: [
      { name: "Heated Pool", icon: "waves", available: true },
      { name: "Ballroom", icon: "music", available: true },
      { name: "Orchid Garden", icon: "trees", available: true },
      { name: "Parking", icon: "car", available: true },
      { name: "WiFi", icon: "wifi", available: true },
      { name: "Wine Cellar", icon: "wine", available: true },
      { name: "Chef Service", icon: "chef-hat", available: true },
    ],
    capacity: { minGuests: 10, maxGuests: 100 },
    pricing: {
      hourly: { "4hr": 18000, "6hr": 24000, "8hr": 30000, "12hr": 40000 },
      fullDay: 55000,
      weekendMultiplier: 1.5,
    },
    foodOptions: [
      { meal: "Breakfast", available: true, price: 500, menu: "Gourmet selection" },
      { meal: "Lunch", available: true, price: 800, menu: "Multi-cuisine" },
      { meal: "Dinner", available: true, price: 1000, menu: "5-star chef menu" },
    ],
    rules: {
      checkInTime: "1:00 PM",
      checkOutTime: "12:00 PM",
      cancellationPolicy: "Free cancellation up to 7 days before check-in",
      securityDeposit: 20000,
      petsAllowed: false,
      alcoholAllowed: true,
      smokingAllowed: false,
    },
    rating: { average: 4.7, count: 156 },
    totalBookings: 287,
    views: 9150,
    featured: true,
    instantBooking: false,
    status: "approved",
    adminId: "admin-006",
    createdAt: "2025-01-20",
  },
];

export const categories = [
  { name: "Swimming Pool", icon: "waves", count: 48 },
  { name: "Sports & Turf", icon: "trophy", count: 35 },
  { name: "Garden Estates", icon: "trees", count: 62 },
  { name: "Luxury Villas", icon: "crown", count: 28 },
  { name: "Pet Friendly", icon: "paw-print", count: 22 },
  { name: "River & Lake", icon: "fish", count: 18 },
  { name: "Party Venues", icon: "music", count: 41 },
  { name: "Family Farms", icon: "heart", count: 55 },
];

export const popularCities = [
  { name: "Lonavala", count: 34, image: "/images/farmhouse-1.jpg" },
  { name: "Karjat", count: 28, image: "/images/farmhouse-2.jpg" },
  { name: "Alibaug", count: 22, image: "/images/farmhouse-3.jpg" },
  { name: "Igatpuri", count: 19, image: "/images/farmhouse-4.jpg" },
  { name: "Panchgani", count: 15, image: "/images/farmhouse-5.jpg" },
  { name: "Nashik", count: 25, image: "/images/farmhouse-6.jpg" },
];

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    avatar: "PS",
    rating: 5,
    comment: "Absolutely loved our stay at Sunset Valley Estate! The pool was amazing and the staff was incredibly helpful. Already planning our next visit.",
    farmhouse: "Sunset Valley Estate",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "Rahul Patel",
    avatar: "RP",
    rating: 5,
    comment: "Perfect weekend getaway with friends. The bonfire setup by the river was magical. FunFarm made the booking process so easy!",
    farmhouse: "Riverside Retreat",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Ananya Desai",
    avatar: "AD",
    rating: 4,
    comment: "The hilltop views were breathtaking. Great amenities and the jacuzzi was the highlight. Highly recommend for couples.",
    farmhouse: "Hilltop Haven",
    date: "3 weeks ago",
  },
  {
    id: 4,
    name: "Vikram Singh",
    avatar: "VS",
    rating: 5,
    comment: "Hosted our company offsite here and it was fantastic. The cricket turf and large spaces made it perfect for team activities.",
    farmhouse: "Green Meadows Farm",
    date: "1 week ago",
  },
];

export const dashboardStats = {
  superAdmin: {
    totalFarmhouses: 156,
    activeFarmhouses: 142,
    totalBookings: 3847,
    monthlyRevenue: 2450000,
    totalUsers: 12540,
    activeAdmins: 89,
    pendingApprovals: 7,
    supportTickets: 23,
  },
  admin: {
    totalBookings: 342,
    pendingRequests: 5,
    monthlyEarnings: 485000,
    occupancyRate: 78,
    averageRating: 4.8,
    totalReviews: 127,
    upcomingBookings: 12,
    repeatCustomers: 45,
  },
  user: {
    totalBookings: 8,
    upcomingBookings: 2,
    wishlistCount: 5,
    totalSpent: 125000,
    reviewsGiven: 6,
    pendingReviews: 2,
  },
};

export const recentBookings = [
  {
    id: "BK-2026-001",
    farmhouse: "Sunset Valley Estate",
    guest: "Priya Sharma",
    date: "Feb 20, 2026",
    duration: "Full Day",
    amount: 32500,
    status: "confirmed",
    guests: 25,
  },
  {
    id: "BK-2026-002",
    farmhouse: "Riverside Retreat",
    guest: "Rahul Patel",
    date: "Feb 22, 2026",
    duration: "8 Hours",
    amount: 9000,
    status: "pending",
    guests: 10,
  },
  {
    id: "BK-2026-003",
    farmhouse: "Hilltop Haven",
    guest: "Ananya Desai",
    date: "Feb 25, 2026",
    duration: "Full Day",
    amount: 28000,
    status: "confirmed",
    guests: 8,
  },
  {
    id: "BK-2026-004",
    farmhouse: "Green Meadows Farm",
    guest: "Vikram Singh",
    date: "Mar 01, 2026",
    duration: "12 Hours",
    amount: 26000,
    status: "pending",
    guests: 40,
  },
  {
    id: "BK-2026-005",
    farmhouse: "Serenity Springs",
    guest: "Meera Reddy",
    date: "Mar 05, 2026",
    duration: "Full Day",
    amount: 14000,
    status: "completed",
    guests: 4,
  },
];

export const monthlyRevenueData = [
  { month: "Sep", revenue: 1800000, bookings: 280 },
  { month: "Oct", revenue: 2100000, bookings: 320 },
  { month: "Nov", revenue: 2400000, bookings: 360 },
  { month: "Dec", revenue: 2800000, bookings: 410 },
  { month: "Jan", revenue: 2300000, bookings: 340 },
  { month: "Feb", revenue: 2450000, bookings: 365 },
];

export const adminsList = [
  { id: "admin-001", name: "Raj Mehta", email: "raj@example.com", farmhouse: "Sunset Valley Estate", plan: "premium", status: "active", bookings: 342, rating: 4.8 },
  { id: "admin-002", name: "Neha Kulkarni", email: "neha@example.com", farmhouse: "Riverside Retreat", plan: "basic", status: "active", bookings: 215, rating: 4.6 },
  { id: "admin-003", name: "Amit Joshi", email: "amit@example.com", farmhouse: "Hilltop Haven", plan: "enterprise", status: "active", bookings: 156, rating: 4.9 },
  { id: "admin-004", name: "Sneha Patil", email: "sneha@example.com", farmhouse: "Green Meadows Farm", plan: "premium", status: "active", bookings: 498, rating: 4.5 },
  { id: "admin-005", name: "Kiran Deshmukh", email: "kiran@example.com", farmhouse: "Serenity Springs", plan: "basic", status: "active", bookings: 98, rating: 4.9 },
  { id: "admin-006", name: "Pooja Nair", email: "pooja@example.com", farmhouse: "Royal Orchid Villa", plan: "enterprise", status: "active", bookings: 287, rating: 4.7 },
];
